takahe/urls.py
from django.conf import settings as djsettings
from django.contrib import admin as djadmin
from django.urls import path, re_path

from activities.views import compose, explore, follows, posts, search, timelines
from api.views import api_router, oauth
from core import views as core
from mediaproxy import views as mediaproxy
from stator import views as stator
from users.views import activitypub, admin, auth, identity, report, settings

from django.conf.urls import include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", core.homepage),
    path("manifest.json", core.AppManifest.as_view()),
    # Activity views
    path("notifications/", timelines.Notifications.as_view(), name="notifications"),
    path("local/", timelines.Local.as_view(), name="local"),
    path("federated/", timelines.Federated.as_view(), name="federated"),
    path("search/", search.Search.as_view(), name="search"),
    path("tags/<hashtag>/", timelines.Tag.as_view(), name="tag"),
    path("explore/", explore.Explore.as_view(), name="explore"),
    path("explore/tags/", explore.ExploreTag.as_view(), name="explore-tag"),
    path(
        "follows/",
        follows.Follows.as_view(),
        name="follows",
    ),
    # Settings views
    path(
        "settings/",
        settings.SettingsRoot.as_view(),
        name="settings",
    ),
    path(
        "settings/security/",
        settings.SecurityPage.as_view(),
        name="settings_security",
    ),
    path(
        "settings/profile/",
        settings.ProfilePage.as_view(),
        name="settings_profile",
    ),
    path(
        "settings/interface/",
        settings.InterfacePage.as_view(),
        name="settings_interface",
    ),
    path(
        "admin/",
        admin.AdminRoot.as_view(),
        name="admin",
    ),
    path(
        "admin/basic/",
        admin.BasicSettings.as_view(),
        name="admin_basic",
    ),
    path(
        "admin/tuning/",
        admin.TuningSettings.as_view(),
        name="admin_tuning",
    ),
    path(
        "admin/policies/",
        admin.PoliciesSettings.as_view(),
        name="admin_policies",
    ),
    path(
        "admin/domains/",
        admin.Domains.as_view(),
        name="admin_domains",
    ),
    path(
        "admin/domains/create/",
        admin.DomainCreate.as_view(),
        name="admin_domains_create",
    ),
    path(
        "admin/domains/<domain>/",
        admin.DomainEdit.as_view(),
    ),
    path(
        "admin/domains/<domain>/delete/",
        admin.DomainDelete.as_view(),
    ),
    path(
        "admin/federation/",
        admin.FederationRoot.as_view(),
        name="admin_federation",
    ),
    path(
        "admin/federation/<domain>/",
        admin.FederationEdit.as_view(),
        name="admin_federation_edit",
    ),
    path(
        "admin/users/",
        admin.UsersRoot.as_view(),
        name="admin_users",
    ),
    path(
        "admin/users/<id>/",
        admin.UserEdit.as_view(),
        name="admin_user_edit",
    ),
    path(
        "admin/identities/",
        admin.IdentitiesRoot.as_view(),
        name="admin_identities",
    ),
    path(
        "admin/identities/<id>/",
        admin.IdentityEdit.as_view(),
        name="admin_identity_edit",
    ),
    path(
        "admin/reports/",
        admin.ReportsRoot.as_view(),
        name="admin_reports",
    ),
    path(
        "admin/reports/<id>/",
        admin.ReportView.as_view(),
        name="admin_report_view",
    ),
    path(
        "admin/invites/",
        admin.Invites.as_view(),
        name="admin_invites",
    ),
    path(
        "admin/hashtags/",
        admin.Hashtags.as_view(),
        name="admin_hashtags",
    ),
    path(
        "admin/hashtags/create/",
        admin.HashtagCreate.as_view(),
        name="admin_hashtags_create",
    ),
    path(
        "admin/hashtags/<hashtag>/",
        admin.HashtagEdit.as_view(),
    ),
    path(
        "admin/hashtags/<hashtag>/delete/",
        admin.HashtagDelete.as_view(),
    ),
    path(
        "admin/stator/",
        admin.Stator.as_view(),
        name="admin_stator",
    ),
    # Identity views
    path("@<handle>/", identity.ViewIdentity.as_view()),
    path("@<handle>/inbox/", activitypub.Inbox.as_view()),
    path("@<handle>/action/", identity.ActionIdentity.as_view()),
    path("@<handle>/rss/", identity.IdentityFeed()),
    path("@<handle>/report/", report.SubmitReport.as_view()),
    # Posts
    path("compose/", compose.Compose.as_view(), name="compose"),
    path(
        "compose/image_upload/",
        compose.ImageUpload.as_view(),
        name="compose_image_upload",
    ),
    path("@<handle>/posts/<int:post_id>/", posts.Individual.as_view()),
    path("@<handle>/posts/<int:post_id>/like/", posts.Like.as_view()),
    path("@<handle>/posts/<int:post_id>/unlike/", posts.Like.as_view(undo=True)),
    path("@<handle>/posts/<int:post_id>/boost/", posts.Boost.as_view()),
    path("@<handle>/posts/<int:post_id>/unboost/", posts.Boost.as_view(undo=True)),
    path("@<handle>/posts/<int:post_id>/delete/", posts.Delete.as_view()),
    path("@<handle>/posts/<int:post_id>/report/", report.SubmitReport.as_view()),
    path("@<handle>/posts/<int:post_id>/edit/", compose.Compose.as_view()),
    # Authentication
    path("auth/login/", RedirectView.as_view(url='/saml2/login', permanent=False), name='login'),
    path("auth/logout/", auth.Logout.as_view(), name="logout"),
    path("auth/signup/", auth.Signup.as_view(), name="signup"),
    path("auth/reset/", auth.TriggerReset.as_view(), name="trigger_reset"),
    path("auth/reset/<token>/", auth.PerformReset.as_view(), name="password_reset"),
    # Identity selection
    path("@<handle>/activate/", identity.ActivateIdentity.as_view()),
    path("identity/select/", identity.SelectIdentity.as_view()),
    path("identity/create/", identity.CreateIdentity.as_view()),
    # Flat pages
    path(
        "about/",
        core.FlatPage.as_view(title="About This Server", config_option="site_about"),
        name="about",
    ),
    path(
        "pages/privacy/",
        core.FlatPage.as_view(title="Privacy Policy", config_option="policy_privacy"),
        name="privacy",
    ),
    path(
        "pages/terms/",
        core.FlatPage.as_view(title="Terms of Service", config_option="policy_terms"),
        name="terms",
    ),
    path(
        "pages/rules/",
        core.FlatPage.as_view(title="Server Rules", config_option="policy_rules"),
        name="rules",
    ),
    # Media/image proxy
    path(
        "proxy/identity_icon/<identity_id>/",
        mediaproxy.IdentityIconCacheView.as_view(),
        name="proxy_identity_icon",
    ),
    path(
        "proxy/identity_image/<identity_id>/",
        mediaproxy.IdentityImageCacheView.as_view(),
        name="proxy_identity_image",
    ),
    path(
        "proxy/post_attachment/<attachment_id>/",
        mediaproxy.PostAttachmentCacheView.as_view(),
        name="proxy_post_attachment",
    ),
    path(
        "proxy/emoji/<emoji_id>/",
        mediaproxy.EmojiCacheView.as_view(),
        name="proxy_emoji",
    ),
    # Well-known endpoints and system actor
    path(".well-known/webfinger", activitypub.Webfinger.as_view()),
    path(".well-known/host-meta", activitypub.HostMeta.as_view()),
    path(".well-known/nodeinfo", activitypub.NodeInfo.as_view()),
    path("nodeinfo/2.0/", activitypub.NodeInfo2.as_view()),
    path("actor/", activitypub.SystemActorView.as_view()),
    path("actor/inbox/", activitypub.Inbox.as_view()),
    path("inbox/", activitypub.Inbox.as_view(), name="shared_inbox"),
    # API/Oauth
    path("api/", api_router.urls),
    path("oauth/authorize", oauth.AuthorizationView.as_view()),
    path("oauth/token", oauth.TokenView.as_view()),
    path("oauth/revoke_token", oauth.RevokeTokenView.as_view()),
    # Stator
    path(".stator/", stator.RequestRunner.as_view()),
    # Django admin
    path("djadmin/", djadmin.site.urls),
    # Media files
    re_path(
        r"^media/(?P<path>.*)$",
        core.custom_static_serve,
        kwargs={"document_root": djsettings.MEDIA_ROOT},
    ),
    path('saml2/', include('djangosaml2.urls')),
]

activities/views/compose.py
from django import forms
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from activities.models import (
    Post,
    PostAttachment,
    PostAttachmentStates,
    PostStates,
    TimelineEvent,
)
from core.files import blurhash_image, resize_image
from core.html import html_to_plaintext
from core.models import Config
from users.decorators import identity_required


@method_decorator(identity_required, name="dispatch")
class Compose(FormView):

    template_name = "activities/compose.html"

    class form_class(forms.Form):
        text = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    "autofocus": "autofocus",
                    "maxlength": Config.lazy_system_value("post_length"),
                    "placeholder": "What's on your mind?",
                },
            )
        )
        visibility = forms.ChoiceField(
            choices=[
                (Post.Visibilities.public, "Public"),
                (Post.Visibilities.local_only, "Local Only"),
                (Post.Visibilities.unlisted, "Unlisted"),
                (Post.Visibilities.followers, "Followers & Mentioned Only"),
                (Post.Visibilities.mentioned, "Mentioned Only"),
            ],
        )
        content_warning = forms.CharField(
            required=False,
            label=Config.lazy_system_value("content_warning_text"),
            widget=forms.TextInput(
                attrs={
                    "placeholder": Config.lazy_system_value("content_warning_text"),
                },
            ),
            help_text="Optional - Post will be hidden behind this text until clicked",
        )
        reply_to = forms.CharField(widget=forms.HiddenInput(), required=False)

        def __init__(self, request, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.request = request
            self.fields["text"].widget.attrs[
                "_"
            ] = f"""
                on load or input
                set characters to my.value.trim().length
                put {Config.system.post_length} - characters into #character-counter

                if characters > {Config.system.post_length} then
                    set #character-counter's style.color to 'var(--color-text-error)'
                    add [@disabled=] to #post-button
                else
                    set #character-counter's style.color to ''
                    remove @disabled from #post-button
                end
            """

        def clean_text(self):
            text = self.cleaned_data.get("text")
            # Check minimum interval
            last_post = self.request.identity.posts.order_by("-created").first()
            if (
                last_post
                and (timezone.now() - last_post.created).total_seconds()
                < Config.system.post_minimum_interval
            ):
                raise forms.ValidationError(
                    f"You must wait at least {Config.system.post_minimum_interval} seconds between posts"
                )
            print(last_post)
            if not text:
                return text
            # Check post length
            length = len(text)
            if length > Config.system.post_length:
                raise forms.ValidationError(
                    f"Maximum post length is {Config.system.post_length} characters (you have {length})"
                )
            return text

    def get_form(self, form_class=None):
        return self.form_class(request=self.request, **self.get_form_kwargs())

    def get_initial(self):
        initial = super().get_initial()
        if self.post_obj:
            initial.update(
                {
                    "reply_to": self.reply_to.pk if self.reply_to else "",
                    "visibility": self.post_obj.visibility,
                    "text": html_to_plaintext(self.post_obj.content),
                    "content_warning": self.post_obj.summary,
                }
            )
        else:
            initial[
                "visibility"
            ] = self.request.identity.config_identity.default_post_visibility
            if self.reply_to:
                initial["reply_to"] = self.reply_to.pk
                if self.reply_to.visibility == Post.Visibilities.public:
                    initial["visibility"] = Post.Visibilities.unlisted
                else:
                    initial["visibility"] = self.reply_to.visibility
                # Build a set of mentions for the content to start as
                mentioned = {self.reply_to.author}
                mentioned.update(self.reply_to.mentions.all())
                mentioned.discard(self.request.identity)
                initial["text"] = "".join(
                    f"@{identity.handle} " for identity in mentioned
                )
        return initial

    def form_valid(self, form):
        # Gather any attachment objects now, they're not in the form proper
        attachments = []
        if "attachment" in self.request.POST:
            attachments = PostAttachment.objects.filter(
                pk__in=self.request.POST.getlist("attachment", [])
            )
        # Dispatch based on edit or not
        if self.post_obj:
            self.post_obj.edit_local(
                content=form.cleaned_data["text"],
                summary=form.cleaned_data.get("content_warning"),
                visibility=form.cleaned_data["visibility"],
                attachments=attachments,
            )
            self.post_obj.transition_perform(PostStates.edited)
        else:
            post = Post.create_local(
                author=self.request.identity,
                content=form.cleaned_data["text"],
                summary=form.cleaned_data.get("content_warning"),
                visibility=form.cleaned_data["visibility"],
                reply_to=self.reply_to,
                attachments=attachments,
            )
            # Add their own timeline event for immediate visibility
            TimelineEvent.add_post(self.request.identity, post)
        return redirect("/")

    def dispatch(self, request, handle=None, post_id=None, *args, **kwargs):
        self.post_obj = None
        if handle and post_id:
            # Make sure the request identity owns the post!
            if handle != request.identity.handle:
                raise PermissionDenied("Post author is not requestor")

            self.post_obj = get_object_or_404(request.identity.posts, pk=post_id)

        # Grab the reply-to post info now
        self.reply_to = None
        reply_to_id = request.POST.get("reply_to") or request.GET.get("reply_to")
        if reply_to_id:
            try:
                self.reply_to = Post.objects.get(pk=reply_to_id)
            except Post.DoesNotExist:
                pass
        # Keep going with normal rendering
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["reply_to"] = self.reply_to
        if self.post_obj:
            context["post"] = self.post_obj
        return context


@method_decorator(identity_required, name="dispatch")
class ImageUpload(FormView):
    """
    Handles image upload - returns a new input type hidden to embed in
    the main form that references an orphaned PostAttachment
    """

    template_name = "activities/_image_upload.html"

    class form_class(forms.Form):
        image = forms.ImageField()
        description = forms.CharField(required=False)

        def clean_image(self):
            value = self.cleaned_data["image"]
            max_mb = settings.SETUP.MEDIA_MAX_IMAGE_FILESIZE_MB
            max_bytes = max_mb * 1024 * 1024
            if value.size > max_bytes:
                # Erase the file from our data to stop trying to show it again
                self.files = {}
                raise forms.ValidationError(f"File must be {max_mb}MB or less")
            return value

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        # Make a PostAttachment
        main_file = resize_image(
            form.cleaned_data["image"],
            size=(2000, 2000),
            cover=False,
        )
        thumbnail_file = resize_image(
            form.cleaned_data["image"],
            size=(400, 225),
            cover=True,
        )
        attachment = PostAttachment.objects.create(
            blurhash=blurhash_image(thumbnail_file),
            mimetype="image/webp",
            width=main_file.image.width,
            height=main_file.image.height,
            name=form.cleaned_data.get("description"),
            state=PostAttachmentStates.fetched,
        )

        attachment.file.save(
            main_file.name,
            main_file,
        )
        attachment.thumbnail.save(
            thumbnail_file.name,
            thumbnail_file,
        )
        attachment.save()
        # Return the response, with a hidden input plus a note
        return render(
            self.request, "activities/_image_uploaded.html", {"attachment": attachment}
        )

templates/activities/_boost.html
{% if post.pk in interactions.boost %}
    <a title="Unboost" class="active" hx-post="{{ post.urls.action_unboost }}" hx-swap="outerHTML">
        <i class="fa-solid fa-retweet"></i>
    </a>
{% else %}
    <a title="Boost" hx-post="{{ post.urls.action_boost }}" hx-swap="outerHTML">
        <i class="fa-solid fa-retweet"></i>
    </a>
{% endif %}

templates/activities/_event.html
{% load activity_tags %}

{% if event.type == "followed" %}
    <div class="follow-banner">
        <a href="{{ event.subject_identity.urls.view }}">
            {{ event.subject_identity.html_name_or_handle }}
        </a> followed you
    </div>
    {% include "activities/_identity.html" with identity=event.subject_identity created=event.created %}
{% elif event.type == "liked" %}
    <div class="like-banner">
        <a href="{{ event.subject_identity.urls.view }}">
            {{ event.subject_identity.html_name_or_handle }}
        </a> liked your post
    </div>
    {% if not event.collapsed %}
    {% include "activities/_post.html" with post=event.subject_post %}
    {% endif %}
{% elif event.type == "mentioned" %}
    <div class="mention-banner">
        <a href="{{ event.subject_identity.urls.view }}">
            {{ event.subject_identity.html_name_or_handle }}
        </a> mentioned you
    </div>
    {% if not event.collapsed %}
    {% include "activities/_post.html" with post=event.subject_post %}
    {% endif %}
{% elif event.type == "boosted" %}
    <div class="boost-banner">
        <a href="{{ event.subject_identity.urls.view }}">
            {{ event.subject_identity.html_name_or_handle }}
        </a> boosted your post
    </div>
    {% if not event.collapsed %}
    {% include "activities/_post.html" with post=event.subject_post %}
    {% endif %}
{% else %}
    Unknown event type {{event.type}}
{% endif %}

templates/activities/_identity.html
{% load activity_tags %}
<div class="post user">

    <a href="{{ identity.urls.view }}">
        <img src="{{ identity.local_icon_url.relative }}" class="icon" alt="Avatar for {{ identity.name_or_handle }}" loading="lazy">
    </a>

    {% if created %}
    <time>
        {{ event.created | timedeltashort }}
    </time>
    {% endif %}

    <a href="{{ identity.urls.view }}" class="handle">
        {{ identity.html_name_or_handle }} <small>@{{ identity.handle }}</small>
    </a>
</div>

templates/activities/_image_uploaded.html
<div class="uploaded-image">
    <input type="hidden" name="attachment" value="{{ attachment.pk }}">
    <img src="{{ attachment.thumbnail_url.relative }}">
    <p>
        {{ attachment.name|default:"(no description)" }}
    </p>
    <div class="buttons">
        <a class="button delete left" _="on click remove closest .uploaded-image">Remove</a>
    </div>
</div>
{% if request.htmx %}
<a class="button add-image"
    hx-get='{% url "compose_image_upload" %}'
    hx-target="this"
    hx-swap="outerHTML"
    _="on load if length of <.uploaded-image/> > 3 then hide me">
    Add Image
</a>
{% endif %}

templates/activities/_menu.html
<nav>
    <a href="/" {% if current_page == "home" %}class="selected"{% endif %} title="Home">
        <i class="fa-solid fa-home"></i> Home
    </a>
    {% if request.user.is_authenticated %}
        <a href="{% url "notifications" %}" {% if current_page == "notifications" %}class="selected"{% endif %} title="Notifications">
            <i class="fa-solid fa-at"></i> Notifications
        </a>
        {% comment %}
        Not sure we want to show this quite yet
        <a href="{% url "explore" %}" {% if current_page == "explore" %}class="selected"{% endif %} title="Explore">
            <i class="fa-solid fa-hashtag"></i> Explore
        </a>
        {% endcomment %}
        <a href="{% url "local" %}" {% if current_page == "local" %}class="selected"{% endif %} title="Local">
            <i class="fa-solid fa-city"></i> Local
        </a>
        <a href="{% url "federated" %}" {% if current_page == "federated" %}class="selected"{% endif %} title="Federated">
            <i class="fa-solid fa-globe"></i> Federated
        </a>
        <a href="{% url "follows" %}" {% if section == "follows" %}class="selected"{% endif %} title="Follows">
            <i class="fa-solid fa-arrow-right-arrow-left"></i> Follows
        </a>
        <h3></h3>
        <a href="{% url "compose" %}" {% if top_section == "compose" %}class="selected"{% endif %} title="Compose">
            <i class="fa-solid fa-feather"></i> Compose
        </a>
        <a href="{% url "search" %}" {% if top_section == "search" %}class="selected"{% endif %} title="Search">
            <i class="fa-solid fa-search"></i> Search
        </a>
        {% if current_page == "tag" %}
        <a href="{% url "tag" hashtag.hashtag %}" class="selected" title="Tag {{ hashtag.display_name }}">
            <i class="fa-solid fa-hashtag"></i> {{ hashtag.display_name }}
        </a>
        {% endif %}
        <a href="{% url "settings" %}" {% if top_section == "settings" %}class="selected"{% endif %} title="Settings">
            <i class="fa-solid fa-gear"></i> Settings
        </a>
    {% else %}
        <a href="{% url "local" %}" {% if current_page == "local" %}class="selected"{% endif %} title="Local Posts">
            <i class="fa-solid fa-city"></i> Local Posts
        </a>
        <a href="{% url "explore" %}" {% if current_page == "explore" %}class="selected"{% endif %} title="Explore">
            <i class="fa-solid fa-hashtag"></i> Explore
        </a>
        <h3></h3>
        {% if config.signup_allowed %}
            <a href="{% url "signup" %}" {% if current_page == "signup" %}class="selected"{% endif %} title="Create Account">
                <i class="fa-solid fa-user-plus"></i> Create Account
            </a>
        {% endif %}
    {% endif %}
</nav>

{% if current_page == "home" %}
    <h2>Compose</h2>
    <form action="/compose/" method="POST" class="compose">
        {% csrf_token %}
        {{ form.text }}
        {{ form.content_warning }}
        <input type="hidden" name="visibility" value="{{ config_identity.default_post_visibility }}">
        <div class="buttons">
            <span id="character-counter">{{ config.post_length }}</span>
            <span class="button toggle" _="on click toggle .enabled then toggle .hidden on #id_content_warning">CW</span>
            <button id="post-button">{% if config_identity.toot_mode %}Toot!{% else %}Post{% endif %}</button>
        </div>
    </form>
{% endif %}

templates/activities/_reply.html
<a title="Reply" href="{{ post.urls.action_reply }}" role="menuitem">
    <i class="fa-solid fa-reply"></i>
</a>

templates/activities/explore_tag.html
{% extends "base.html" %}

{% block title %}#{{ hashtag.display_name }} Timeline{% endblock %}

{% block content %}
<div class="timeline-name">Explore Trending Tags</div>

<section class="icon-menu">
    {% for hashtag in page_obj %}
        {% include "activities/_hashtag.html" %}
    {% empty %}
        No tags are trending yet.
    {% endfor %}

</section>
{% endblock %}

templates/activities/federated.html
{% extends "activities/local.html" %}

{% block title %}Federated Timeline{% endblock %}

templates/activities/follows.html
{% extends "base.html" %}
{% load activity_tags %}

{% block subtitle %}Follows{% endblock %}

{% block content %}
    <div class="view-options">
        {% if inbound %}
            <a href=".">Your Follows ({{ num_outbound }})</a>
            <a href="." class="selected">Follows You ({{ num_inbound }})</a>
        {% else %}
            <a href=".?inbound=true" class="selected">Your Follows ({{ num_outbound }})</a>
            <a href=".?inbound=true">Follows You ({{ num_inbound }})</a>
        {% endif %}
    </div>

    <section class="icon-menu">
        {% for identity in page_obj %}
            <a class="option" href="{{ identity.urls.view }}">
                <img src="{{ identity.local_icon_url.relative }}" loading="lazy">
                <span class="handle">
                    {{ identity.html_name_or_handle }}
                    <small>@{{ identity.handle }}</small>
                </span>
                {% if identity.id in outbound_ids %}
                    <span class="pill">Following</span>
                {% endif %}
                {% if identity.id in inbound_ids %}
                    <span class="pill">Follows You</span>
                {% endif %}
                <time>{{ identity.follow_date | timedeltashort }} ago</time>
            </a>
        {% empty %}
            <p class="option empty">You have no follows.</p>
        {% endfor %}
    </section>

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a class="button" href=".?page={{ page_obj.previous_page_number }}{% if inbound %}&amp;inbound=true{% endif %}">Previous Page</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="button" href=".?page={{ page_obj.next_page_number }}{% if inbound %}&amp;inbound=true{% endif %}">Next Page</a>
        {% endif %}
    </div>
{% endblock %}

templates/activities/home.html
{% extends "base.html" %}
{% load activity_tags %}

{% block title %}Home{% endblock %}

{% block content %}
    {% for event in page_obj %}
        {% if event.type == "post" %}
            {% include "activities/_post.html" with post=event.subject_post %}
        {% elif event.type == "boost" %}
            <div class="boost-banner">
                <a href="{{ event.subject_identity.urls.view }}">
                    {{ event.subject_identity.html_name_or_handle }}
                </a> boosted
                <time>
                    {{ event.subject_post_interaction.published | timedeltashort }} ago
                </time>
            </div>
            {% include "activities/_post.html" with post=event.subject_post %}
        {% endif %}
    {% empty %}
        Nothing to show yet.
    {% endfor %}

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a class="button" href=".?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="button" href=".?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </div>
{% endblock %}

templates/activities/local.html
{% extends "base.html" %}

{% block title %}Local Timeline{% endblock %}

{% block content %}
    {% for post in page_obj %}
        {% include "activities/_post.html" with feedindex=forloop.counter %}
    {% empty %}
        No posts yet.
    {% endfor %}

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a class="button" href=".?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="button" href=".?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </div>
{% endblock %}

templates/activities/notifications.html
{% extends "base.html" %}

{% block title %}Notifications{% endblock %}

{% block content %}
    <div class="view-options">
        {% if notification_options.followed %}
            <a href=".?followed=false" class="selected"><i class="fa-solid fa-check"></i> Followers</a>
        {% else %}
            <a href=".?followed=true"><i class="fa-solid fa-xmark"></i> Followers</a>
        {% endif %}
        {% if notification_options.boosted %}
            <a href=".?boosted=false" class="selected"><i class="fa-solid fa-check"></i> Boosts</a>
        {% else %}
            <a href=".?boosted=true"><i class="fa-solid fa-xmark"></i> Boosts</a>
        {% endif %}
        {% if notification_options.liked %}
            <a href=".?liked=false" class="selected"><i class="fa-solid fa-check"></i> Likes</a>
        {% else %}
            <a href=".?liked=true"><i class="fa-solid fa-xmark"></i> Likes</a>
        {% endif %}
        {% if notification_options.mentioned %}
            <a href=".?mentioned=false" class="selected"><i class="fa-solid fa-check"></i> Mentions</a>
        {% else %}
            <a href=".?mentioned=true"><i class="fa-solid fa-xmark"></i> Mentions</a>
        {% endif %}
    </div>

    {% for event in events %}
        {% include "activities/_event.html" %}
    {% empty %}
        No notifications yet.
    {% endfor %}

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a class="button" href=".?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="button" href=".?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </div>
{% endblock %}

templates/activities/post_delete.html
{% extends "base.html" %}

{% block title %}Delete Post{% endblock %}

{% block content %}
    <h1>Delete this post?</h1>
    {% include "activities/_mini_post.html" %}
    <form action="." method="POST">
        {% csrf_token %}
        <a class="button" onclick="history.back()">Cancel</a>
        <button class="delete">Delete</button>
    </form>

{% endblock %}